/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package uni.example;

import org.junit.jupiter.api.*;
import static org.junit.jupiter.api.Assumptions.assumeTrue;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.CsvSource;


class CalculatorTests {
    Calculator calculator;

    @BeforeAll
    static void initAll(){}

    @BeforeEach
    void init(){
        calculator = new Calculator();
    }

    @Test
    @Disabled("for demonstration purposes")
    void skippedTest(){}    // not executed

    @Test
    void abortedTest(){
        assumeTrue("abc".contains("Z"));
        fail("test should have been aborted");
    }

    @AfterEach
    void tearDown(){}

    @AfterAll
    static void tearDownAll(){}

    @Test
    void addition(){
        assertEquals(9, calculator.add(4, 5));
    }

    @Test
    @DisplayName("1 + 1 = 2")
    void addsTwoNumbers(){
        assertEquals(2, calculator.add(1, 1), "1 + 1 should equal 2");
    }

    @ParameterizedTest(name = "{0} + {1} = {2}")
    @CsvSource({
            "0, 1, 1",
            "1, 2, 3",
            "49, 51, 100",
            "1, 100, 101"
    })
    void add(int first, int second, int expectedResult){
        assertEquals(expectedResult, calculator.add(first, second),
                ()-> first + " + " + second + " should equal " + expectedResult);
    }

    @Test
    void assertTrueTest(){
        assertTrue(4<5);
    }

    @Test
    void assertFalseTest(){
        assertFalse(4>5);
    }


}
