/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package uni.example;

public class Calculator {
    public int add(int a, int b) {
        return a + b;
    }

    public static void main(String[] args) {
        System.out.println("This is a simple calculator application.");
    }
}
